/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tubespbowithgui;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author ASUS
 */
public class ViewIntro2 extends javax.swing.JFrame {

    /**
     * Creates new form ViewIntro2
     */
    public ViewIntro2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IntroScreen2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IntroScreen2.setBackground(new java.awt.Color(0, 0, 0));
        IntroScreen2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel5.setText("Di lantai 5, kamu akan melawan salah satu monster penjaga menara");
        IntroScreen2.add(jLabel5);
        jLabel5.setBounds(140, 150, 770, 24);

        jButton6.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jButton6.setText("Start the Game");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        IntroScreen2.add(jButton6);
        jButton6.setBounds(380, 400, 180, 51);

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel12.setText("Terdapat 10 lantai dalam menara. Sang puteri berada di lantai paling atas");
        IntroScreen2.add(jLabel12);
        jLabel12.setBounds(120, 100, 810, 24);

        jLabel13.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel13.setText("Di lantai terakhir, kamu akan melawan ketua bandit yang menculik sang putri");
        IntroScreen2.add(jLabel13);
        jLabel13.setBounds(90, 200, 840, 24);

        jLabel14.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel14.setText("Tiap class yang dipilih mempunyai kapasitas yang berbeda-beda.");
        IntroScreen2.add(jLabel14);
        jLabel14.setBounds(170, 300, 730, 24);

        jLabel15.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel15.setText("Good Luck!");
        IntroScreen2.add(jLabel15);
        jLabel15.setBounds(410, 340, 320, 24);

        jLabel45.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\TubesPBOwithGUI251223\\TubesPBOwithGUI\\src\\img\\sCROLL.png")); // NOI18N
        jLabel45.setText("jLabel45");
        IntroScreen2.add(jLabel45);
        jLabel45.setBounds(-120, -50, 1150, 570);

        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\TubesPBOwithGUI251223\\TubesPBOwithGUI\\src\\img\\theophile-curto-twfbetc-x4size.jpg")); // NOI18N
        jLabel27.setText("jLabel27");
        IntroScreen2.add(jLabel27);
        jLabel27.setBounds(0, 0, 950, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IntroScreen2, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IntroScreen2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewIntro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewIntro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewIntro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewIntro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewIntro2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IntroScreen2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
    
    public JButton getBtn6() {
        return jButton6;
    }

    public void setBtn6(JButton jButton6) {
        this.jButton6 = jButton6;
    }
    public void addActionListener(ActionListener e){
        jButton6.addActionListener(e);
    }
    
    public void setTextLabel12(String text) {
        jLabel12.setText(text);
    }

    public void setTextLabel13(String text) {
        jLabel13.setText(text);
    }

    public void setTextLabel14(String text) {
        jLabel14.setText(text);
    }

    public void setTextLabel15(String text) {
        jLabel15.setText(text);
    }

    public void setTextLabel27(String text) {
        jLabel27.setText(text);
    }

    public void setTextLabel45(String text) {
        jLabel45.setText(text);
    }

    public void setTextLabel5(String text) {
        jLabel5.setText(text);
    }

    public JLabel getLabel12() {
        return jLabel12;
    }

    public JLabel getLabel13() {
        return jLabel13;
    }

    public JLabel getLabel14() {
        return jLabel14;
    }

    public JLabel getLabel15() {
        return jLabel15;
    }

    public JLabel getLabel27() {
        return jLabel27;
    }

    public JLabel getLabel45() {
        return jLabel45;
    }

    public JLabel getLabel5() {
        return jLabel5;
    }
}
